// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // tsx is required because generator `prisma-client` emits TypeScript source
    // (not compiled JS), so the seed script cannot run under plain `node`.
    // Dev-only dependency - never bundled into the production build.
    //
    // Invoked through its CLI entrypoint rather than as a bare `tsx` command:
    // the Prisma CLI spawns this without npm's node_modules/.bin PATH injection,
    // so on Windows a bare `tsx` fails with "not recognized as a command".
    seed: "node node_modules/tsx/dist/cli.mjs prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
