// GENERATED by tools/gen-fy26-constants.js — do not edit by hand.
// Source: FY26组织结构.xlsx (mtime 2026-07-21T07:55:09.915Z, 31 data rows, 7 depts / 24 sections)

export interface Fy26OrgRow {
  readonly dept: string;
  readonly section: string | null;   // null => department-level 责任者 (部长)
  readonly managerName: string;
  readonly managerEmail: string;
  readonly rowIndex: number;         // becomes sortOrder
}

export const FY26_ORG_ROWS: readonly Fy26OrgRow[] = [
  { dept: '经营企画部', section: null, managerName: '岸本 恵典', managerEmail: 'keisuke.kishimoto.dmwx@cn.denso.com', rowIndex: 1 },
  { dept: '经营企画部', section: '财务课', managerName: '谢鹏', managerEmail: 'peng.xie.dmwx@cn.denso.com', rowIndex: 2 },
  { dept: '经营企画部', section: '企画课', managerName: '陈露', managerEmail: 'lu.chen.dmwx@cn.denso.com', rowIndex: 3 },
  { dept: '安全人力资源部', section: null, managerName: '孙娟', managerEmail: 'juan.sun.dmwx@cn.denso.com', rowIndex: 4 },
  { dept: '安全人力资源部', section: '人事课', managerName: '孙娟', managerEmail: 'juan.sun.dmwx@cn.denso.com', rowIndex: 5 },
  { dept: '安全人力资源部', section: '总务课', managerName: '李家云', managerEmail: 'jiayun.li.dmwx@cn.denso.com', rowIndex: 6 },
  { dept: '安全人力资源部', section: '安全环境课', managerName: '周晨', managerEmail: 'chen.zhou.dmwx@cn.denso.com', rowIndex: 7 },
  { dept: '安全人力资源部', section: '情报系统课', managerName: '薛平', managerEmail: 'ping.xue.dmwx@cn.denso.com', rowIndex: 8 },
  { dept: '生管调达部', section: null, managerName: '沈坚东', managerEmail: 'jiandong.shen.dmwx@cn.denso.com', rowIndex: 9 },
  { dept: '生管调达部', section: '调达课', managerName: '张敏', managerEmail: 'min.zhang.dmwx@cn.denso.com', rowIndex: 10 },
  { dept: '生管调达部', section: '生产管理1课', managerName: '王江霞', managerEmail: 'jiangxia.wang.dmwx@cn.denso.com', rowIndex: 11 },
  { dept: '生管调达部', section: '生产管理2课', managerName: '王玲燕', managerEmail: 'lingyan.wang.dmwx@cn.denso.com', rowIndex: 12 },
  { dept: '生管调达部', section: '制部品管理课', managerName: '王玲燕', managerEmail: 'lingyan.wang.dmwx@cn.denso.com', rowIndex: 13 },
  { dept: '品质保证部', section: null, managerName: '卞小勇', managerEmail: 'xiaoyong.bian.dmwx@cn.denso.com', rowIndex: 14 },
  { dept: '品质保证部', section: '部品品质课', managerName: '朱育姗', managerEmail: 'yushan.zhu.dmwx@cn.denso.com', rowIndex: 15 },
  { dept: '品质保证部', section: '品质企画课', managerName: '蔡仙平', managerEmail: 'xianping.cai.dmwx@cn.denso.com', rowIndex: 16 },
  { dept: '品质保证部', section: '品质保证课', managerName: '朱育姗', managerEmail: 'yushan.zhu.dmwx@cn.denso.com', rowIndex: 17 },
  { dept: '品质保证部', section: '检査课', managerName: '陈红', managerEmail: 'hong.chen.dmwx@cn.denso.com', rowIndex: 18 },
  { dept: '生产技术部', section: null, managerName: '王雪东', managerEmail: 'xuedong.wang.dmwx@cn.denso.com', rowIndex: 19 },
  { dept: '生产技术部', section: '生产技术1课', managerName: '徐明江', managerEmail: 'mingjiang.xu.dmwx@cn.denso.com', rowIndex: 20 },
  { dept: '生产技术部', section: '生产技术2课', managerName: '张小燕', managerEmail: 'xiaoyan.zhang.dmwx@cn.denso.com', rowIndex: 21 },
  { dept: '生产技术部', section: '生产技术3课', managerName: '陈力', managerEmail: 'li.chen.dmwx@cn.denso.com', rowIndex: 22 },
  { dept: '制造支援部', section: null, managerName: '王建春', managerEmail: 'jianchun.wang.dmwx@cn.denso.com', rowIndex: 23 },
  { dept: '制造支援部', section: '保全课', managerName: '顾杰', managerEmail: 'jie.gu.dmwx@cn.denso.com', rowIndex: 24 },
  { dept: '制造支援部', section: 'TIE课', managerName: '华振', managerEmail: 'zhen.hua.dmwx@cn.denso.com', rowIndex: 25 },
  { dept: '制造支援部', section: '制造企画课', managerName: '潘琦', managerEmail: 'qi.pan.dmwx@cn.denso.com', rowIndex: 26 },
  { dept: '制造部', section: null, managerName: '周晓明', managerEmail: 'xiaoming.zhou.dmwx@cn.denso.com', rowIndex: 27 },
  { dept: '制造部', section: '生产1课', managerName: '姚驰锦', managerEmail: 'chijin.yao.dmwx@cn.denso.com', rowIndex: 28 },
  { dept: '制造部', section: '生产2课', managerName: '王鸿科', managerEmail: 'hongke.wang.dmwx@cn.denso.com', rowIndex: 29 },
  { dept: '制造部', section: '生产3课', managerName: '杨英梅', managerEmail: 'yingmei.yang.dmwx@cn.denso.com', rowIndex: 30 },
  { dept: '制造部', section: '生产4课', managerName: '孙金花', managerEmail: 'jinhua.sun.dmwx@cn.denso.com', rowIndex: 31 },
];
